# Numpy and Plotly Examples

In [1]:
import numpy as np
import plotly.express as px

## Scatter Plot and Contour Plot

In [30]:
x = np.array([[1,2],
              [3,4],
              [5,6]])

In [31]:
w = np.array([3,2])
b = -5.4 * 13
np.linalg.norm(w)

3.605551275463989

In [32]:
x.dot(w)

array([ 7, 17, 27])

In [33]:
x.dot(w) + b

array([-63.2, -53.2, -43.2])

In [ ]:
np.sign()

### Create Random Data

In [2]:
n_a = 100
x_a = np.random.normal(loc=-1, scale=1, size=(n_a,2))
z_a = np.zeros(n_a)

In [3]:
n_b = 50
x_b = np.random.normal(loc=1, scale=0.3, size=(n_b, 2))
z_b = np.ones(n_b)

In [4]:
x = np.concatenate((x_a, x_b))
z = np.concatenate((z_a, z_b))

### Define Function $f(x)$

In [42]:
def f(x):
    """ Residual from Hyperplane defined by w and b
    
    Argument: x -- numpy-array of size (n, 2)
    Return value: np.array of size n
    """
    w = np.array([3., 2.])
    b = -19.5
    return x.dot(w) + b

In [43]:
x = np.array([[4.5, 3],
              [5, 3],
              [4, 3]])
f(x)

array([ 0. ,  1.5, -1.5])

### Create a Meshgrid

In [6]:
x0_min, x0_max = x[:, 0].min() -1, x[:, 0].max() + 1
x1_min, x1_max = x[:, 1].min() -1, x[:, 1].max() + 1
h = 0.1 # stepsize in meshgrid
xx, yy = np.meshgrid(np.arange(x0_min, x0_max, h), np.arange(x1_min, x1_max, h))

### Create $z$ values from $f$

In [8]:
#z = f(np.c_[xx.ravel(), yy.ravel()])
xx

array([[-4.14847632, -4.04847632, -3.94847632, ...,  2.45152368,
         2.55152368,  2.65152368],
       [-4.14847632, -4.04847632, -3.94847632, ...,  2.45152368,
         2.55152368,  2.65152368],
       [-4.14847632, -4.04847632, -3.94847632, ...,  2.45152368,
         2.55152368,  2.65152368],
       ...,
       [-4.14847632, -4.04847632, -3.94847632, ...,  2.45152368,
         2.55152368,  2.65152368],
       [-4.14847632, -4.04847632, -3.94847632, ...,  2.45152368,
         2.55152368,  2.65152368],
       [-4.14847632, -4.04847632, -3.94847632, ...,  2.45152368,
         2.55152368,  2.65152368]])

In [ ]:
def set_color(z):
    if z == 0:
        return "a"
    elif z == 1:
        return "b"
    else:
        return "else"

px.scatter(
    data_frame=x,
    x=x[:,0],
    y=x[:,1],
    color=list(map(set_color,z)),
    color_discrete_map={"a":"green", "b":"red", "else":"blue"}
)

In [ ]:
np.c_()